// Code generated by "stringer -type=CMD,PUSH_KIND,PROTO -output=cons_string.go"; DO NOT EDIT

package comm

import "fmt"

const _CMD_name = "PINGENTERLEAVEPUBMSGSPUSH"

var _CMD_index = [...]uint8{0, 4, 9, 14, 17, 21, 25}

func (i CMD) String() string {
	i -= 1
	if i >= CMD(len(_CMD_index)-1) {
		return fmt.Sprintf("CMD(%d)", i+1)
	}
	return _CMD_name[_CMD_index[i]:_CMD_index[i+1]]
}

const _PUSH_KIND_name = "NOTIFYDISPLAY"

var _PUSH_KIND_index = [...]uint8{0, 6, 13}

func (i PUSH_KIND) String() string {
	i -= 1
	if i >= PUSH_KIND(len(_PUSH_KIND_index)-1) {
		return fmt.Sprintf("PUSH_KIND(%d)", i+1)
	}
	return _PUSH_KIND_name[_PUSH_KIND_index[i]:_PUSH_KIND_index[i+1]]
}

const _PROTO_name = "TCPHTTPSVRWS"

var _PROTO_index = [...]uint8{0, 3, 7, 10, 12}

func (i PROTO) String() string {
	i -= 1
	if i < 0 || i >= PROTO(len(_PROTO_index)-1) {
		return fmt.Sprintf("PROTO(%d)", i+1)
	}
	return _PROTO_name[_PROTO_index[i]:_PROTO_index[i+1]]
}
